App\Entity\User:
  attributes:
    id:
      groups: [user_read]
    name:
<<<<<<< HEAD
      groups: [user_read, user_register, user_update]
    email:
      groups: [user_read, user_register]
    password:
      groups: [user_register]
=======
      groups: [user_read, user_post]
    email:
      groups: [user_read, user_post]
    password:
      groups: [user_post]
>>>>>>> master
    avatar:
      groups: [user_read]
    active:
      groups: [user_read]
    token:
      groups: [user_activate]
    createdAt:
      groups: [user_read]
    updatedAt:
      groups: [user_read]
<<<<<<< HEAD
    groups:
      groups: [user_read]
=======
>>>>>>> master
